### ISSUE TITLE
shhh! could you be quiteter?

### ISSUE THREAD

**Issue by alekksander** [Cimbali/CleanLinks#1]
please consider adding options to disable red count badge on icon, and notifications (they are very nice and system integrated, just not needed for some).

——

As this is „n°1” issue, i'd like to say THANK YOU. Glad someone finally picked up this great project.

**Comment by Cimbali** [comment]
The red count badge visually displays the difference between event delegation mode (i.e. "on click") and the page-cleaning mode. I think we should keep the badge but I might be able to tweak the color to something less intrusive.

I'll also add an option for disabling notifications.
