### ISSUE TITLE
Req: How to configure so downloads at sourceforge.net work properly.

### ISSUE THREAD

**Issue by FredThompsonII** [Cimbali/CleanLinks#10]
What needs to be added so sourceforge.net downloads work and the web browser does not revert to the file listing page on sourceforge.net?

adding these to the whitelist is insufficient:

fsdn.com
slashdotmedia.com
sourceforge.net

**Comment by Cimbali** [comment]
Adding just this worked for me: downloads.sourceforge.net (downloading astyle, if this didn't work please tell me which project you're trying to download from).

In general I'd say look in the list of recently cleaned links to find which should not have been cleaned. (I know it's kind of hard to fish out the link you need with all the ads that pollute the list on that page.)
