### ISSUE TITLE
4.1.2 UI issue

### ISSUE THREAD

**Issue by khabib227** [Cimbali/CleanLinks#107]
I just download the 4.1.2 now, and first I want thanks for the new "rules origin" feature, very good. Now the issue, I use FF 67 with e10s disabled, because I have low memory. Using a clean profile the UI is so:

![cl](https://user-images.githubusercontent.com/61421212/78200042-cb52b180-7463-11ea-97b7-abd7552eeced.jpg)

**Comment by Cimbali** [comment]
Ok, that shouldn’t happen. What’s your screen resolution?

**Comment by khabib227** [comment]
1366 x 768, Win 7

**Comment by Cimbali** [comment]
Hmmm, but your window is not 768px high on this screenshot, is it? What I get when I have a small window is that the popup overflows rather than being cut off.

**Comment by khabib227** [comment]
My resolution is 1366 x 768, is because I cropped the screenshot, I removed the taskbar,

**Comment by Cimbali** [comment]
Hi @khabib227, this should be fixed now. Can you try it before I release the fix?

Here's a step by step guide:
- get the [source code](https://github.com/Cimbali/CleanLinks/archive/51e94b95655db5796f135f0656773f58c7d3c1d5.zip) (this is the zip download from the "Clone or download" button on the repo’s main page) and extract the zip
    - alternately you can clone the repository, in that case make sure to pull the latest changes
- disable your current cleanlinks in your browser
- type `about:debugging#addons` in your firefox address bar
- tick "Enable add-on debugging"
- click "Load Temporary Addon"
- select the `manifest.json` file from the source code you just extracted

**Comment by khabib227** [comment]
Hi @Cimbali, here seem fixed! Thank so much!

**Comment by Cimbali** [comment]
Keeping this open for now as I’m not completely satisfied with that fix.

**Comment by khabib227** [comment]
thank so much
