### ISSUE TITLE
javascript:; links are broken

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#111]
What I see in the log:

```
null; 
-> javascript:;
```

**Comment by Cimbali** [comment]
Can you give an example of where this happens? We should be avoiding most of those lines already so I need the exact value of the `href` to know why it doesn't work. Also which version are you using?

**Comment by birdie-github** [comment]
Looks like you've already fixed this in version 4.1.5. Thank you!

**Comment by birdie-github** [comment]
Found another instance where such links get broken and there's nothing in the log:

https://bugzilla.kernel.org/show_bug.cgi?id=205227

When I click "reply" nothing happens.

**Comment by Cimbali** [comment]
Alright so the bug here is really that it doesn’t appear in the log:
- There is a valid link, `#add_comment`
- There is a javascript event modifying the behaviour of that link 

So CleanLinks prevents the modification on that link, as it should. You can add a rule to allow javascript modifying links, either just for `bugzilla.kernel.org` or for `*.*`

**Comment by birdie-github** [comment]
> You can add a rule to allow JavaScript modifying links

Sorry, I've no idea how to do that.

**Comment by Cimbali** [comment]
From the settings page,
- either select the `*.*` rule,
- or create a new one
  - click `Add rule`
  - Put domain `bugzilla.kernel.org`
  - Leave path empty
- in the “Cleaning Actions“ part, tick `allow javascript to modify links`
- click `Save rule`

**Comment by birdie-github** [comment]
To be honest I frequent at least a dozen of websites which use such links and I'm not a fan of this solution :-(

**Comment by Cimbali** [comment]
Yes, that’s on its way! See https://github.com/Cimbali/CleanLinks/issues/104#issuecomment-612649837
