### ISSUE TITLE
Add an option for resetting rules which does NOT delete the custom rules.

### ISSUE THREAD

**Issue by Rtizer-9** [Cimbali/CleanLinks#112]
Recently I was modifying a particular rule and had to delete it but accidentally deleted one more rule which got selected after it.

Now, to bring that default rule the only option I had was to use "reset rules" which unfortunately also removes every custom rule. So an option which bring the default state of default rules WITHOUT interfering the custom rules would be of great help.

**Comment by Cimbali** [comment]
Hmmm. That does sound interesting.

Currently default vs. custom rules are identified as being (or not being) in the default rules file of the add-on, so I think this could easily be done.

In the mean time, here’s a little work-around to merge rules outside of CleanLinks with `jq`:

1. export your current rules (before reset) to `a.json`
2. reset rules
3. export your default rules (after reset) to `b.json`
4. merge files with `jq -s '.[0] * .[1]' a.json b.json > c.json`
5. import `c.json`

**Comment by Cimbali** [comment]
I guess an “undo” button would also fit your needs? That would cover more use cases as well.

**Comment by Cimbali** [comment]
In the end I’ve also added a “Reset Default Rules” button.
