### ISSUE TITLE
v4 block google/youtube search result

### ISSUE THREAD

**Issue by motfis** [Cimbali/CleanLinks#113]
I just update clean link to v4.* and now everytime i tried to make search in google/youtube. The search result is blocked when typing in the box, does not retun any results.
If I turn off cleanlinks, google search works.

**Comment by Cimbali** [comment]
Sorry I’m not sure I get what’s not working. Is it the search results suggestion?

**Comment by motfis** [comment]
Hi Cimbali, yes, I mean the search results suggestion.

**Comment by motfis** [comment]
Hi Cimbali,
Any updates regarding this bug?

**Comment by Cimbali** [comment]
Hi @motfis, not yet I’m afraid. You can probably just open the log of cleaned links by clicking on the addon icon, selecting the right cleaned element (should be google.com/search/complete or something like that) and the click on the green shield with the green checkmark at t he bottom of the popup.

**Comment by Cimbali** [comment]
This seems fixed in the current master now. Feel free to reopen if the net release (which will be 4.2.0) does not actually fix this (in which case we’ll need more details, browser version etc.)
