### ISSUE TITLE
LiveJournal redirect whitelisting again in version 4.2.0

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#118]
Looks like version 4.2.0 has broken it:

https://www.livejournal.com/misc/get_domain_session.bml?return=https%3A%2F%2FXXXXXXXXXX.livejournal.com%2F&sign=LONG_HEX_NUMBER&t=NUMBER -> https://XXXXXXXXXX.livejournal.com/

Please fix.

**Comment by Cimbali** [comment]
Hi,

Is this 4.2.0 or 4.2.1? 4.2.0 has an issue that hides default rules.

Can you upgrade to the latter and if that does not fix it, click the "Reset Default Rules" button in the rules editor?

**Comment by birdie-github** [comment]
After updating and resetting all rules (don't know which one has helped fixed the problem) the bug is now gone.
