### ISSUE TITLE
Facebook cft query parameter suggestion

### ISSUE THREAD

**Issue by cgcgcgcgcg** [Cimbali/CleanLinks#125]
Thanks to your amazing extension (and with a little help of another query parameter for the syntax) I can Copy clean link and be able to paste it quickly, which is vital for group admins/mods.

This is the parameter that -along with existing ones- cleans fb links completely:
`__cft__[a-zA-Z_%\[\]0-9]*`
![ksnip_20201212-234438](https://user-images.githubusercontent.com/38960370/101995637-1354f400-3cd4-11eb-8035-0810c69ed380.png)

**Comment by W1B7** [comment]
https://www.facebook.com/marion.schnura?__cft__[0]=AZWPgXH5qc0T83uTOpYtfF0qWWN7sK15XHpEyOoonRJ1co1Ft5yGX-iy2nmEtXpdbTYeF_SZJqvXOJHr9ek9F5Kma1WG3DXnZaMqz7ZsaQPETRnjm0Qwu6GjNxyeBTCIb4dxYV9HeqduC-ECEyAQfCeXFzh-TaS9Q3FQAtxVQ1jKag&__tn__=-a]-R
