### ISSUE TITLE
Clean Links on FF 84.0 won't whitelist sites

### ISSUE THREAD

**Issue by WillPittenger** [Cimbali/CleanLinks#126]
I added to FlagFox an option to generate a QR Code using [Google's Chart API](http://chart.apis.google.com/), but CleanLinks keeps cleaning the link.  I managed to get CleanLink to add a rule to prevent that, but that rule doesn't seem to have worked.  The FlagFox setting would be generating the URL `http://chart.apis.google.com/chart?cht=qr&chs=300x300&chl={fullURL}`.  `{fullURL}` returns the URL of the destination encoded.

I see the rules below.  The second one I added manually when the first, generated by the extension, didn't work.
```
*.piwik.openstreetmap.org/^/piwik.php$
*.chart.apis.google.com//chart?cht=qr&*
```
Could you tell me what's wrong?  I liked the old Link Cleaner that died when Firefox Quantum forced the end of XUL.

**Comment by Cimbali** [comment]
I liked the old Link Cleaner too ! But it seems @diegocr didn’t have the time or energy to rewrite everything from scratch in the new add-on system.

---

So you’re trying to have a link like this, am I right?

    http://chart.apis.google.com/chart?cht=qr&chs=300x300&chl=https://piwik.openstreetmap.org/piwik.php

Whitelisting works for me, simply by selecting the cleaned link in the popup’s interface and clicking the button with the green checkmark at the bottom of the screen. This is what the rule looks like:

- domain `chart.apis.google.com`
- path `^/chart$`
- Whitelist query parameters (prevent removing and allow embedded URL): `chl`

Here’s a screenshot (greyed out cleaning items are inherited fro parent rules, here only `*.*`), and don’t forget to press the *Save rule* button after modifying it

![image](https://user-images.githubusercontent.com/6126377/102690845-8dbbd180-4208-11eb-8b08-2390db0027e9.png)

**Comment by WillPittenger** [comment]
Ah.  Thanks.
