### ISSUE TITLE
I don't think I'll ever understand the rules

### ISSUE THREAD

**Issue by jawz101** [Cimbali/CleanLinks#127]
Is there a way to take a different approach?  Block everything and then have some sort of mechanism to create exceptions on the fly?  Every time I look at the little pop-up I see so many things slip through that are unnecessary for a page to work.

I don't know if it is the interface or how web pages function but rule building confuses me.
I can understand regex, create uBlock Origin rules, NoScript, uMatrix, but what this does loses me.

Are there any video tutorials or other ways to tackle this visually?

**Comment by Cimbali** [comment]
Hi @jawz101 and sorry for the confusion the rules are causing.

So far, all we have as documentation are 3 wiki pages:
- on the [interface](https://github.com/Cimbali/CleanLinks/wiki/Interface)
- on the [rules themselves](https://github.com/Cimbali/CleanLinks/wiki)
- on [how to whitelist](https://github.com/Cimbali/CleanLinks/wiki/Whitelisting) a page or URL.

I can see if there’s a way to add some other documentation, maybe a video tutorial can be a good idea indeed.

Another avenue could be to change the syntax of the rules, do you think that could be helpful? Currently we’re able to export them to [this uBlock-like format](https://cimbali.github.io/CleanLinks/export.html) that is used by NeatURL. Do you think an interface to edit the rules in this format could be more helpful to you ?

**Comment by jawz101** [comment]
Oooh I like the Interface instructions.  For the rules page, could you maybe include a little example of the rule that would remove the thing to be removed?

And is there a way to temporarily comment out a rule?
Does the pop-up display all that _could_ be touched or just the things the rules are triggering?
