### ISSUE TITLE
Huge CPU load

### ISSUE THREAD

**Issue by Peuj** [Cimbali/CleanLinks#13]
Hello,

With CleanLinks enabled, Firefox use a lot of CPU and so become slow and laggy.
Once I disable CleanLinks, the problem is gone.
Note, I use the default options.

I didn't make a lot of tests like disabling some options, identify some specific websites, or disabling some others incompatible add-ons.
If I have more detailed information I'll provide here.

Really good extension but not usable for me right now.

Thanks

**Comment by Cimbali** [comment]
Alright, well CleanLinks only reacts to events, and does so at 3 places by default, maximum 4:
- clicks (should not cause overhead)
- document loaded (If event delegation is *de*activated)
- receiving headers (if "redirect watcher" is activated)
- outgoing requests (if "clean outgoing HTTP requests" is activated)

There is no "background" work at all. Every time we check an URL we mainly try a bunch of regexes. There is an argument to be made that we could reduce work (i.e. a request from a click on a link is already cleaned) if necessary.

Now if you have a lot of tabs open or they self-refresh a lot (or some ads/trackers contained in the page), then conceivably the last 2 could cause some overhead. Maybe unselecting those in the preferences is a good start.

**Comment by Peuj** [comment]
> ...you have a lot of tabs open or they self-refresh a lot (or some ads/trackers contained in the page), then conceivably the last 2 could cause some overhead. Maybe unselecting those in the preferences is a good start.

Exactly what I suspect. There are many notifications for cleaned links that appear on a same site.

I'll male some tests and let you know.

**Comment by Cimbali** [comment]
Also before 8019c1ccc3fe4dfd284096e3275aa05afaa67cb2 the history of cleaned links was infinite (now max 100 items), so make sure you use the latest version for your tests. :)

**Comment by Peuj** [comment]
I use the version 3.04b :)

With only 1 tab open on a specific site, the site loading never ends and Firefox use 20% CPU.

If I disable the option _**Clean outgoing HTTP requests**_ and reload the tab, the problem is gone.

**Comment by alekksander** [comment]
@Peuj how to reproduce exactly? specific example could be useful. personally experienced similar thing, but not sure if it's CL related

**Comment by Cimbali** [comment]
We could be repeatedly cleaning the same page that redirects to itself, or worse, several instances of this infinite loop. Do you have a website that does this so we can reproduce? In my experience I've never had infinite loops, at worst "The page isn't redirecting properly" errors.

**Comment by Cimbali** [comment]
Well it seems oglaf.com (not entirely sfw) has an infinite-ish age redirection: after loading, the page checks if cookies not set and, if not, uses javascript to redirect to a portal on the same website with a return URL to the current page.

So because it's not a page directly redirecting to itself with HTTP headers, instead using javascript, we don't get the "The page isn't redirecting properly" error.
