### ISSUE TITLE
Clarify Name: 'CleanLinks' vs 'Clean Links'

### ISSUE THREAD

**Issue by shanepeleg** [Cimbali/CleanLinks#130]
I noticed that there is an inconsistency when it comes to the name of this plugin.  Most of the time it refers to itself as "CleanLinks" (no space), however it is listed as "Clean Links" (with space) under addons.mozilla.org and occasionally in the docs.

**Comment by Cimbali** [comment]
I’ve updated the add-on page (I vaguely remember it didn’t let me use the CleanLinks name initially, but it’s a long time ago so I’m not completely sure). Feel free to PR the name correction wherever I missed it.

**Comment by shanepeleg** [comment]
I think you got everything. Thanks!
