### ISSUE TITLE
Clean URLs in youtube description

### ISSUE THREAD

**Issue by madpipeline** [Cimbali/CleanLinks#135]
I've tried looking into creating my own rule, but don't understand how the regex is to be formed.

Example page: ```https://www.youtube.com/watch?v=dV7csY0mRgM```

In it's description there are several links, all of them formed like this:

```https://www.youtube.com/redirect?event=video_description&redir_token=QUFFLUhqbmoxbGoyTG80MFZMdXdHOGc3OXliVi1zMWItd3xBQ3Jtc0trWElFNTBlQjJBODJPYkQwdUlOSkZZUGh0cXdPakg1ZDViektvdm4tYXpMUDFzRFpiQ0FWTWczQ2pEYlNqbmNRUkdPV29jN3JHeXhub0xIaTQ4eGFYN2UtbDljREFvWW1McG5vS1k4SG5KODBxYjl3NA&q=https%3A%2F%2Fwww.recorder.ro%E2%80%8B%E2%80%8B```

All these links should be cleaned and shown like this:

```https://www.recorder.ro​​```

I've tried looking through the existing rules and I think groups are used, but I'm not sure how.

Some examples in the wiki would be useful, but also this rule could be part of the default rules.

**Comment by Cimbali** [comment]
They seem to be cleaned automatically − are you sure it’s not the case ? In that case you might have whitelisted something (maybe accidentally).

- To test the addon’s cleaning mechanism with out-of-the-box rules, you can use https://cimbali.github.io/CleanLinks/
  Copying and pasting the link you provide there and clicking « Clean it! » correctly cleans the link.
- Clicking the link from the page you suggest also works for me, with the addon popup indicating the link was cleaned :
 
  ![image](https://user-images.githubusercontent.com/6126377/121425427-ae244780-c972-11eb-9190-331917bd08f2.png)

- Rules are for white listing, i.e. preventing the cleaning of some links. Not sure which rules you have but you can filter them − try looking at all links that contain `youtube`. There’s rather few global rules.

Can you confirm the link is not cleaned ?

**Comment by madpipeline** [comment]
Ok, I think I misunderstood how this extension works.

If I open the youtube page, and hover over the links in the description, I'm still shown the tracking link.

However, if I click on the link, I see the it doesn't take me to the tracking link , but takes me directly to the target link.

This is slightly confusing. Is this the expected behavior?

**Comment by Cimbali** [comment]
Yes, that’s the expected behaviour ! It allows to:
- not have to parse all the page thus limit accessing user data
- clean links that are not explicitely contained on the page (redirects, javascript-created links on the fly, etc.)

**Comment by Cimbali** [comment]
By the way @madpipeline you can access the clean link without opening it by right-clicking the link and using « Copy Clean Link » (if the feature « copy clean links from the context menu » is enabled).

**Comment by madpipeline** [comment]
Thank you.
