### ISSUE TITLE
CleanLinks disables open link in a new tab

### ISSUE THREAD

**Issue by Frescootje** [Cimbali/CleanLinks#152]
CleanLinks 4.2.3 disables opening a link in a new tab in Firefox 103. Now, only Command-Click does the job (Mac). As soon as I disable CleanLinks, opening a link in a new tab with a single click is working again as it should be.

**Comment by Cimbali** [comment]
Yes, that is intended behaviour. You can deactivate that from the options − it’s called “Allowed links to different tabs”
