### ISSUE TITLE
Add-On started causing 'The page isn’t redirecting properly' error

### ISSUE THREAD

**Issue by manek43509** [Cimbali/CleanLinks#155]
Since installing CleanLinks I started getting the following error on several pages across multiple devices:

`The page isn’t redirecting properly
An error occurred during a connection to [www.manek.org.uk](http://www.manek.org.uk/).

   This problem can sometimes be caused by disabling or refusing to accept cookies.`

I've had to disable the extension, which is a pity as I thought it was a really cool idea.

**Comment by Cimbali** [comment]
That error message is typically what you get from a redirect loop. The page redirects you to a page that contains its own URL, or a URL of the same website, then CleanLinks identifies that embedded URL and redirects you to it. In the end, after 20 attempts, your browser gives up and displays this message.

We try to identify automatically most legitimate use-cases, such as login pages that want to memorise where you were before. However, we invariably miss some, as we auto-detect embedded URLs, but can only guess which pages should or should not contain embedded URLs. Typically we match on words such as login or auth, but yours is called “password-protection” so it evades the default whitelist.

If you click on the CleanLinks toolbar, you’ll see a popup with all redirect activity logged, like this:

![image](https://user-images.githubusercontent.com/6126377/215715851-12b7ba06-b367-4b1a-bfe7-e620ac4bcf28.png)

Here you see you’re indeed in a loop and the use case is legitimate, so you can click any of the repeated items in the list, and then click the green checkmark at the button to add it to your whitelist. This page will then never show that issue again for you.

There’s a lot more details on the wiki: [how CleanLinks works](https://github.com/Cimbali/CleanLinks/wiki), [a breakdown of the interface](https://github.com/Cimbali/CleanLinks/wiki/Interface#cleanlinks-interface), and more.
