### ISSUE TITLE
[Bug] find_click_target doesn't handle href if null

### ISSUE THREAD

**Issue by OdinVex** [Cimbali/CleanLinks#156]
Some websites I've come across cause `./inject.js` to throw an error in the `find_click_target` code block, specifically in its attempt to access href. Sometimes it is null. It's uncommon to find a site with it set to null, I've only found it on a few and only in logged-in sessions. I addressed it by checking for href === null and simply returning `node`.

**Comment by Cimbali** [comment]
Thanks for suggesting!
