### ISSUE TITLE
cleanlinks „disable” is ignored

### ISSUE THREAD

**Issue by alekksander** [Cimbali/CleanLinks#16]
1. go:
https://polishannoyancefilters.netlify.com/issues

2. select disable from extensions popup

3. click:
„Oficjalne Polskie Filtry do AdBlocka, uBlocka i AdGuarda.”

result:
link is cleaned and redirects to [url with text](https://raw.githubusercontent.com/MajkiIT/polish-ads-filter/master/polish-adblock-filters/adblock.txt)

expected:
abp:subscribe handling by the browser

(side suggestion:
have abp:subscribe hardcoded as whitelist)

**Comment by Cimbali** [comment]
This was fixed but not shipped yet. Corrected now in 3.0b5.
