### ISSUE TITLE
URL query parameters are not removed

### ISSUE THREAD

**Issue by nerone** [Cimbali/CleanLinks#24]
In "Remove From Links" field enter **ref**.
Only URL query parameter’s **name** is removed, leaving parameter’s **value** in URL. E.g. http://example.org/?ref=value is cleaned to http://example.org/?=value.
Expected result should be http://example.org/

Reproducible here: https://jsfiddle.net/8L52o4qw/2/

**Comment by Cimbali** [comment]
Good catch.
