### ISSUE TITLE
Would it be better to rewrite the URLs in the page?

### ISSUE THREAD

**Issue by different55** [Cimbali/CleanLinks#26]
So that the browser's standard "Copy link address" button works without needing to add another specialized button for it.

**Comment by Cimbali** [comment]
The goal of the 2 buttons is to have one to copy the cleaned link, and one to copy the original link.

Furthermore, we already clean the links in the document by default, but it can't catch all of the links to clean. Unless we watch the href and onclick (and similar events) on all links, buttons, etc  to catch links changing dynamically, and then all javascript that adds such objects to the document. but that's kind of heavy. So I was thinking of removing the ability to clean in the document itself feature actually.
