### ISSUE TITLE
CL remains unstoppable, whitelisting ignored

### ISSUE THREAD

**Issue by alekksander** [Cimbali/CleanLinks#28]
1. go to https://audiosciencereview.com/forum/index.php and select register
2. notice at Verification that validation box is not there
3. whitelist:
![cbug](https://user-images.githubusercontent.com/3148302/43713950-a6d7b90a-997b-11e8-87a1-188ea11629b5.png)
4. refresh. w3 is not on in popup anymore but extension icon still displays „1” (not visible on screenshot below, sry). whitelisted entry is also missing from skipped domains in CL settings. CL is unstoppable, therefore on the page the validation box still not present
![cbug2](https://user-images.githubusercontent.com/3148302/43714115-3efc117c-997c-11e8-9618-195c8733df30.png)
5. disabling extension solves problem

**Comment by alekksander** [comment]
false alarm, i can't reproduce anymore. sorry.

**Comment by alekksander** [comment]
@Cimbali 
another whitelist ignored.
go:
https://imgops.com/i.imgur.com/Dr2QZWF.png
and click express on →  pixlr [express] 

again no matter how many times, the whitelisted item is ignored

**Comment by Cimbali** [comment]
AFAICT there is no bug there:
- Clicking the link cleans it and brings to `imgops.com`
- Whitelisting once whitelists `apps.pixlr.com`.
- Going back one page and click the link again, correctly brings `apps.pixlr.com` which then redirects to `pixlr.com`, with again `imgops.com` in the URL. Thus CleanLinks cleans this second link and brings to `imgops.com` again.
- Whitelisting a second time now whitelists `pixlr.com`
- Going back and clicking again, the browser opens the `pixlr.com` page as expected.

**Comment by alekksander** [comment]
i end up at http://imgops.com/

**Comment by Cimbali** [comment]
Can you check the last items in your whitelist?

**Comment by alekksander** [comment]
there is only apps.pixlr.com
but when it redirects me to imgops.com CL has new redirection. if i whitelist it pixlr.com is added. then i manually go back to the 
 https://imgops.com/i.imgur.com/Dr2QZWF.png
and it works fine on next clicks

so it's not bug after all, but it's confusing. i imagine there is no walk around this for regular user

**Comment by alekksander** [comment]
i'm afraid solution is out of my knowledge here, but if i have to use my imagination i'd say CL should analyze link for further redirects before it does the first one, and perhaps list them all with different color (like light yellow, or something else specified in „?”), so when user ends up at imgops.com list shows there was a presumed further redirection that could be whitelisted. it's just an idea, i guess it's additional work for mechanisms with relatively rare application for user.
