### ISSUE TITLE
Doesnt Work on ip-check.info

### ISSUE THREAD

**Issue by Kraxys** [Cimbali/CleanLinks#33]
My Browser (FF ESR 60 64 bit on W7) remains stuck on the homepage of the site http://ip-check.info .

Whitelisting this site doesn't help.

How to make CleanLinks works on this site, sending me on the results page?

**Comment by Cimbali** [comment]
Which link do you click that doesn't bring you to the desired page? I've tried with ff 61.0.2 and I get full IP info etc by clicking the "start test" button on the home page.

**Comment by Kraxys** [comment]
Whether I click on Check it!/Test your anonymity, on the displayed IP, or on *"Please click here to start the full anonymity test and see all results"*, same thing: I'm stuck on this homepage, unable to get the results page. I just tried many times with a fresh FF 60 ESR with no other addon.

**Comment by Cimbali** [comment]
Does anything appear in the list of cleaned links? What platform are you on?

**Comment by Cimbali** [comment]
Can’t reproduce this issue.
