### ISSUE TITLE
Add option to hide number from icon

### ISSUE THREAD

**Issue by kotoko** [Cimbali/CleanLinks#35]
CleanLinks shows number of cleaned links on the extension icon. I propose to add option, to hide this number.

**Comment by Cimbali** [comment]
Hi @kotoko I’m unsure why this would be useful. That number seems like a discrete indicator of the add-on activity. Is it distracting or something like that?

**Comment by Kravimir** [comment]
@kotoko If you don't want to see the number, why not just pin the extension icon to the overflow menu?

**Comment by kotoko** [comment]
I hide all possible numbers from extension icons because they are distracting me (and this number/info is useless to me - I prefer extensions that are working in background). I don't hide this icon in extra menu because I would need +1 click if I want open un-cleaned link. For me it would be usefull but maybe I'm in minority?

I opened this issue a while ago. Today I'm not using Clean Links in firefox because it made too many broken links for me. So I guess if nobody else mentions this problem then there is no reason to implement it.
