### ISSUE TITLE
Are all the permissions really required?

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#37]
From the Mozilla add-on webpage:

Permissions

This add-on can:
* Access your data for all websites
* **Input data to the clipboard**
* **Display notifications to you**

I'm curious if the last two are really required.

**Comment by Cimbali** [comment]
Input data to the clipboard is necessary for copying cleaned links. We get the text under the mouse when the button is clicked, then clean the link and put the result in the clipboard.

The notifications is required to show notifications. This is disabled by default, as it can get intrusive, and probably could be removed completely.
