### ISSUE TITLE
Enable subdomains matching for "Skip Domains"

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#39]
When you exclude a certain domain ("Skip Domains"), e.g.

    youtube.com

its subdomains are still matched, e.g.

    www.youtube.com

That's counterintuitive.

**Comment by Cimbali** [comment]
Yes, we match fully qualified domains. We could add a wildcard form, but I don't think that should be enabled from the quick-whitelisting option from the cleaned links history popup.

**Comment by birdie-github** [comment]
I guess people editing options manually are smart enough to understand what they're doing but it's really up to you. Maybe a better solution would be to allow to enter something like

    *.domain.com

**Comment by Cimbali** [comment]
Yes that's what I'm saying, we could make this possible but only when you're editing the options directly.

**Comment by birdie-github** [comment]
Sounds good to me but I remember that you were concerned about subdomains leaking information, so I'm not so sure any more ;-)

It's really up to you then.

**Comment by Cimbali** [comment]
The whole rule system has been overhauled. Matching subdomains is now a toggle on every rule, and does not require writing regular expressions anymore.
