### ISSUE TITLE
make notification popup time longer or customizable

### ISSUE THREAD

**Issue by jawz101** [Cimbali/CleanLinks#4]
It just flickers on and off too quickly.  Eventually I just disabled it but if I did have it on I'd want to see what it says.

**Comment by jawz101** [comment]
... this issue may not really be that important, to be honest.  I end up quickly turning notifications off.  They're just so annoying so having them stay any longer would do nothing for me, at least.

**Comment by Cimbali** [comment]
Yeah adding a setting is real easy though so that's already in the works. Not sure it doesn't completely break the notifications yet.

I think at current we clean to many things and in the long run there'll be less notifications.
