### ISSUE TITLE
Please extend the notification popup

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#40]
Currently it only shows 

    Link cleaned!

    URL

I would like it to show:

    Page URL: https://blabla.com
    Original URL: https://blabla.com/url=https://another.domain
    Cleaned URL: https://another.domain

Page URL is required because processing might occur in a background tab/another Firefox window.

**Comment by birdie-github** [comment]
I don't believe notifications pose any security risk, so let's close #37.

**Comment by Cimbali** [comment]
There is really a high rate of links being cleaned. I think maybe notifications should be removed entirely.
