### ISSUE TITLE
Domain whitelisting via menu

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#41]
It would be great if the add-on allowed to white list domains (for simplicity sake the domain of the address bar) via its menu or alternatively, each domain which matches the rewrite rules.

**Comment by Cimbali** [comment]
This is already possible.

Clicking on the CleanLinks icon opens a popup with the list of cleaned links. You can then select any cleaned link and click the "Whitelist Selection" button, which will add the origin's domain to the whitelist.

**Comment by OdinVex** [comment]
> This is already possible.
> 
> Clicking on the CleanLinks icon opens a popup with the list of cleaned links. You can then select any cleaned link and click the "Whitelist Selection" button, which will add the origin's domain to the whitelist.

That doesn't at all seem to be allowing for a domain, it seems to only allow a single URL. Edit: It's also completely useless for certain kinds of authentication. Home Assistant? Forget it, just disable CleanLinks. Matching all subdomains and `^.*$` path with "Allow (allowlist) URL embedded inside path` enabled and `Allow javashit to modify links` enabled with nothing else won't even address the issue.
