### ISSUE TITLE
Reduntant youtube embeds rewrites

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#42]
https://www.youtube.com/embed/MuehR3WuZ_E

Each 3 or 4 seconds produces:

https://www.youtube.com/api/stats/playback?ns=yt&el=embedded&cpn=H0fKd5ib6Vj5Ccu-&docid=MuehR3WuZ_E&ver=2&referrer=https%3A%2F%2Fwww.youtube.com%2Fembed%2FMuehR3WuZ_E&cmt=0.192&plid=AAV23H4P4rBjNhQY&ei=h_-sW9DGEMKXgAfM1LKIDA&fmt=244&fs=0&rt=0.996&of=gz14kY-A0c1t2FUxEZbQLw&euri&lact=1001&cl=214291029&mos=0&vm=CAEQABgE&volume=100&c=WEB_EMBEDDED_PLAYER&cver=20180921&cplayer=UNIPLAYER&cbr=Firefox&cbrver=62.0&cos=Windows&cosver=10.0&hl=en_US&cr=GB&len=105&fexp=23710476%2C23718325%2C23721698%2C23721898%2C23723207%2C23726563%2C23728347%2C23733751%2C23737832%2C23744176%2C23749835%2C23751767%2C23752869%2C23753283%2C23753597%2C23755886%2C23755898%2C23756720%2C23758198%2C23759694%2C23760180%2C23762063%2C23762650%2C23762813%2C23763126%2C23763475%2C23763691%2C23764134%2C23764670%2C23764993%2C23766071%2C23766882%2C23767275%2C23767582%2C9440546%2C9449243%2C9463154%2C9475651%2C9485000&rtn=8&afmt=251&size=952%3A1920&inview=1
→ https://www.youtube.com/embed/MuehR3WuZ_E

This rule fixes it:

    youtube\.com\/api\/

**Comment by Cimbali** [comment]
This is youtube collecting statistics on your activity, and blocking these kind of requests is one of the reasons for this add-on.

**Comment by birdie-github** [comment]
I can imagine that watching a two hours video will produce close to 2400 messages in the log which could affect memory usage and performance but if you think it's OK, then close this bug report. ;-)

**Comment by Cimbali** [comment]
The number will keep increasing, but the actual history of cleaned links is always limited to 100 items per tab.

https://github.com/Cimbali/CleanLinks/blob/32b605cfe08fb3b89adce0d4e1f819446cea50d1/addon/background.js#L139-L142

Stopping these kind of links is not a catch-all answer for privacy, but definitely an improvement. Especially for other pages that track you in the same way, but on which you might not be streaming content, or from a different domain than the one from which you stream, etc.
