### ISSUE TITLE
Cleaning Google's URL tracking

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#45]
Google follows you through search results pages using the ei={22 random chars} get parameter, e.g.

https://www.google.com/search?q=nintendo+switch&client=firefox-b-ab&ei=XXXXXXXXXXXXXXXXXXXXXXXXX&start=10&sa=N

I wonder if you could strip it.

**Comment by Cimbali** [comment]
This is an interesting direction to go in, but first requires that we can operate URL cleaning and parameter cleaning separately (#27).

**Comment by Cimbali** [comment]
This is now done with the new cleaning mechanism that will be released in v4. Test it at https://cimbali.github.io/CleanLinks/
