### ISSUE TITLE
Cleaning of URL tracking for Twitter embeds doesn't seem to work

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#46]
Steps to reproduce:

Go to https://www.gsmarena.com/google_pixel_3___3_xl_price_and_full_review_leaks_with_iphone_xs_max_camera_shootout-news-33625.php

Click the embedded image in the tweet -> you'll be redirected to

https://twitter.com/jon_prosser/status/1048260765105442816/photo/1?ref_src=twsrc%5Etfw%7Ctwcamp%5Etweetembed%7Ctwterm%5E1048260765105442816%7Ctwgr%5E363937393b70726f64756374696f6e&ref_url=https%3A%2F%2Fwww.gsmarena.com%2Fgoogle_pixel_3___3_xl_price_and_full_review_leaks_with_iphone_xs_max_camera_shootout-news-33625.php

**Comment by Cimbali** [comment]
It seems twitter.com is in the whitelist for "skipped domains". This can only be refined once #27 is resolved.

**Comment by Cimbali** [comment]
This is now correctly handled, with ref_xxx parameters removed.
