### ISSUE TITLE
suggestions for the whitelisting pop-up

### ISSUE THREAD

**Issue by jawz101** [Cimbali/CleanLinks#5]
I don't understand what the whitelisting box is telling me.  For one, it scrunches up the left-side and right-side so I don't know what the full url's are.  Additionally, I don't know what the left-hand and right-hand sections actually mean.

Could maybe on hover it show the full url string so I can read the whole line item?  And can the left-side and right-side have descriptions above them so I know what this is telling me?

**Comment by Cimbali** [comment]
The left and right hand side should currently have titles, respectively "Original Link" and "Cleaned Link". It might be a font color thing; I'll check that. Can you provide a screenshot for reference?

I'll try to throw in the full url on hover as well.

**Comment by Cimbali** [comment]
Yeah seems like white-on-white.

As a side note the 5th link seems terribly cleaned (yet the 100th which is similar looks alright).
