### ISSUE TITLE
LiveJournal pages are inaccessible

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#51]
E.g.

https://comment-fic.livejournal.com

https://www.livejournal.com/misc/get_domain_session.bml?return=https%3A%2F%2Fcomment-fic.livejournal.com%2F&sign=XXXXXXXXXXXXXXXXXXXXXXXXXXX&t=1111111111111

-> https://comment-fic.livejournal.com/

Since Clean Links doesn't support wildcards or checking against top level domain, it gets tedious to work with LJ because you have to whitelist each individual third-level domain you're ever going to visit.

**Comment by nerone** [comment]
It's true "Skip Domains" option doesn't support wildcards (same as in original CleanLinks extension).
But adding regex to "Skip Links matching with", e.g. livejournal\.com, should solve the issue.
Alternatively, unchecking "Clean outgoing HTTP requests" should also do the trick, if that is "under-the-hood" request.

**Comment by Cimbali** [comment]
I’d like to add this to the rules.json that contains the new rules, but I’m not sure what needs to happen as I don’t use livejournal. Any insight into what it does or how it functions would be welcome.

**Comment by birdie-github** [comment]
1. You open

`https://comment-fic.livejournal.com/`

2. It redirects to

`https://www.livejournal.com/misc/get_domain_session.bml?return=https%3A%2F%2Fcomment-fic.livejournal.com%2F&sign=RANDOM_HEX_STRING&t=UNIX_TIMESTAMP`

3. It redirects to

`https://comment-fic.livejournal.com/__setdomsess?dest=https%3A%2F%2Fcomment-fic.livejournal.com%2F&k=ljdomsess.comment-fic&v=v1%3Au12345678%3As45%3AtUNIX_TIMESTAMP%3ARANDOM_HEX_STRING%2F%2F1`

4. It then redirects back to

https://comment-fic.livejournal.com/

So it looks like we need to have two exceptions:

`www.livejournal.com/misc/get_domain_session.bml% (SQL notation)`
and
`%.livejournal.com/__setdomsess%`

Or probably something a little bit more intelligent 'cause they may change the names of these scripts however I'm looking at these two redirects and I cannot find anything particular about them. Both contain `dom` and `sess` ;-) Probably we should skip them based on `?return=` and `?dest=` - this looks like the best option.

I've whitelisted the entire domain for myself, just to avoid any other possible errors - `\.livejournal\.com`.
