### ISSUE TITLE
Can't login in PayPal.

### ISSUE THREAD

**Issue by ArenaL5** [Cimbali/CleanLinks#53]
## Issue
After I log-in with my username and password in PayPal, CleanLinks redirects me continually, to the point  it forces me to solve a Captcha to prove I'm not a bot flooding PayPal. After I complete this Captcha, of course, it redirects me again and forces me to do another Captcha.

The problem request seems to follow this template (forgive my typos, I'm still learning to use Clean Links and I copied this by hand):

`https://www.paypal.com/authflow/twofactor/returnUri=signin&country.x=XXX&locale.x=XXX&nonce=XXX&stsReturnUrl=https%3A%2F%2Fwww.paypal.com%2Fsignin%2F&mkey=XXX`

CleanLinks finds the embedded URL `https://www.paypal.com/signin/` and tries to redirect me there.

Either whitelisting the domain `www.paypal.com` or adding `\bsignin\b` to the whitelist regexp apparently avoids this problem.

## Thanks
Thank you for your plugin. I'm still trying a lot of plugins (outside of uBlock Origin) to avoid tracking in URLs, but yours has _another_ feature I'm interested in: to force pages to open in the current tab, which is a plus.

**Comment by Cimbali** [comment]
This is fixed maybe a little conservatively. We protect the `stsReturnUrl` but it might be purely for statistics (guessing from the `sts` prefix and the fact that a `returnUri` parameter is also present), so ideally we should try removing it instead, and see if that breaks the system or not. I don’t have 2FA on paypal however.
