### ISSUE TITLE
onMouseover tooltips and number of redirects invisible in Android

### ISSUE THREAD

**Issue by ArenaL5** [Cimbali/CleanLinks#55]
Firefox Android doesn't display icon buttons in the toolbar; rather, it displays text buttons in a popup menu.

It would be much appreciated if you could add the number of accepted redirects in the text button, as uBlock Origin does (see bottom of the screenshot):

![screenshot_20181206-172952](https://user-images.githubusercontent.com/37388405/49597566-9bc98d00-f974-11e8-9550-c3095357634d.png)

Also, in the options page for Clean Links (the one at `about:addons`), every feature you can enable displays a tooltip when hovering the mouse over it. These tooltips are easy to miss with a mouse and impossible to read with a touchscreen: just displaying the explanation before the option (or behind a clickable (?) button) would be better.

EDIT: Please ignore the referenced issue, I couldn't find my issue and I submitted it _again... to the old repo._

**Comment by Cimbali** [comment]
Related to  #30 and #32

**Comment by Cimbali** [comment]
This has been fixed with the v4.1 release.
