### ISSUE TITLE
Amazon not cleaning?

### ISSUE THREAD

**Issue by n-o-o-b** [Cimbali/CleanLinks#56]
Just installed the extension and was trying it out on Amazon. It doesn't seem to be doing any cleaning.

I compared a product page with Clean Links enabled and then with another similar extension I have, [Neat URL](https://addons.mozilla.org/en-GB/firefox/addon/neat-url).

With Clean Links I get this:

https://www.amazon.co.uk/Expert-Workwear-Visibility-Waistcoat-Pockets/dp/B072395LQ5/ref=sr_1_4?ie=UTF8&qid=1544548795&sr=8-4&keywords=hi+vis

With Neat URL I get this:
https://www.amazon.co.uk/Expert-Workwear-Visibility-Waistcoat-Pockets/dp/B072395LQ5

**Comment by Cimbali** [comment]
This add-on removes redirects. There are none in your link.

**Comment by n-o-o-b** [comment]
So you are saying that Neat URL and Clean Links have different purposes?

**Comment by Cimbali** [comment]
Exactly.
We remove redirects, they remove useless parameters. Ideally CleanLinks should do both, but I don't have enough time to extend it right now (PRs are always welcome!)

An example, take the following link:
`https://www.google.com/url?sa=t&[...]&url=https%3A%2F%2Fwww.amazon.es%2F&usg=AOvVaw2fvwiWaCMKbEtPof3eFeuj`

CleanLinks will replace it with `https://www.amazon.es/`

NeatURL* will replace it with `https://www.google.com/url?url=https%3A%2F%2Fwww.amazon.es%2F`

---

\* Disclaimer: only illustrating the different purposes of the addons, I didn't actually go test NeatURL.

**Comment by n-o-o-b** [comment]
Okay, that makes sense now. Almost. What I don't understand is, where does the first link come from? Google search?

**Comment by Cimbali** [comment]
Yes this is an example I've taken from searching "amazon" in the spanish google, hence amazon.es
