### ISSUE TITLE
Issue on the new url matching

### ISSUE THREAD

**Issue by duguyipiao** [Cimbali/CleanLinks#58]
I updated to the new version today (v3.2.2 with firefox 64.0.2). I have some issue on the new url matching.

For example: the link
https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&ved=2ahUKEwixrZf_1ZLgAhVSM-wKHTHpDNoQFjABegQICxAB&url=https%3A%2F%2Fzh.wikipedia.org%2Fzh%2F%25E6%25B1%2589%25E8%25AF%25AD&usg=AOvVaw0mqDLH5lZh4X5OQ4ypirn4
should be cleaned as
https://zh.wikipedia.org/zh/%E6%B1%89%E8%AF%AD
or
https://zh.wikipedia.org/zh/汉语
however, I get
https://zh.wikipedia.org/zh/

**Comment by Cimbali** [comment]
Thanks for reporting the issue! I've shipped the fix and published the new version, you can update the add-on again.

**Comment by duguyipiao** [comment]
It's fixed. Thanks!
