### ISSUE TITLE
how to ignore/disable on local IP

### ISSUE THREAD

**Issue by yannakos** [Cimbali/CleanLinks#60]
how to ignore/disable on local IP
when i add 192.168.1.2 in the ignore rules is no effect

**Comment by Cimbali** [comment]
You can add to "Skip domains" `,localhost,127.0.0.1,192.168.1.2`, basically the comma-separated list of all the addresses you might use for your local machine. Check in the cleaned links history which hostname or IP address shows up.

**Comment by yannakos** [comment]
Thankyou for your quick answer, i will test it when i back to home =)

**Comment by azrdev** [comment]
I cannot find an option "Skip domains" on v4.2.3 , I guess https://github.com/Cimbali/CleanLinks/commit/0b1a1815461d4e91e1f019cd3c46ca4bfbcddb4b removed it in favor of rules -- but adding a rule for an IP doesn't seem to catch, so what do?
