### ISSUE TITLE
CleanLinks alters Facebook open in new tab/window behaviour

### ISSUE THREAD

**Issue by wyaqoob** [Cimbali/CleanLinks#61]
Hi, fantastic extension. I've noticed that CleanLinks alters FB's current open in new tab behaviour, i.e. clicking a link in FB normally opens the link a new tab. But with CleanLink active the link opens in the current tab. Is this intended behaviour?

**Comment by Cimbali** [comment]
Ah, interesting. I think we intend to respect that but it's not always easy if we alter the link at click time (which is the only way we can show the yellow background feedback on the link).

Can you provide your platform and browser versions?

**Comment by wyaqoob** [comment]
Sure, thanks. Mac OS X 10.14.3, Firefox 66.0b13, and latest version of CleanLinks.

**Comment by Cimbali** [comment]
Can’t seem to reproduce for now, with Firefox 72 and the latest master. i’ll put this off until after the next release as it is a relatively minor issue.

**Comment by Cimbali** [comment]
Tested on macOS Firefox 73 and 74 with the latest Clean Links release, and facebook links open in new tab as expected. Please reopen if you can reproduce this bug specifying how.
