### ISSUE TITLE
Can't login via SAML2.0 / Shibboleth

### ISSUE THREAD

**Issue by johnp** [Cimbali/CleanLinks#66]
Logging in to a website using SAML2.0 / Shibboleth using the HTTP-Redirect binding can set the `SigAlg` query parameter to the canonical URI of the signature algorithm [1], e.g.:

https://samltest.id/idp/profile/SAML2/Redirect/SSO?SAMLRequest=[base64-request]&RelayState=samltest&Signature=[base64-signature]&SigAlg=http%3A%2F%2Fwww.w3.org%2F2001%2F04%2Fxmldsig-more%23rsa-sha256

`^http:\/\/www\.w3\.org\/` should probably be whitelisted to not be redirected to, since I suspect there are more protocols out there that do this kind of thing. Maybe something less drastic is possible.

[1] https://www.iana.org/assignments/xml-security-uris/xml-security-uris.xhtml

**Comment by Cimbali** [comment]
Thanks for reporting ! In the mean time you can simply whitelist the origin domain.

**Comment by Cimbali** [comment]
This is still waiting to be fixed as I can’t seem to figure out whether there is any commonality in the URLs for SAML2.0 login services. If for example there is always one of SAML2 or SSO or Shibboleth that’s probably enough to whitelist the `SigAlg` parameter.
