### ISSUE TITLE
[Regression 3.2.7] IMDB links are no longer cleaned

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#68]
?ref_= is not cleaned any longer. That's a regression.

To verify I've just downgraded to 3.2.6 and links are being cleaned again.

Also links which contain utm_source utm_medium utm_campaign and alike.

**Comment by Cimbali** [comment]
Yup, we’re not modifying links that do not have redirects, at least for now. Doing so was a bug. Especially since there’s no separate way of whitelisting parameters separately.
We’ll revisit this when we have a separate redirect and parameter cleaning.

**Comment by nerone** [comment]
Query parameter cleaning is very useful feature to get rid of URL tracking.

Will have to stick to version 3.2.6 for now.

**Comment by Cimbali** [comment]
Rules are now set differently, with redirects and cleaning parameters separated. `ref_` is now removed again from imdb.

I still need to finish consolidating the rules and improve the interface to edit them before I release what will be CleanLinks v4. In the mean time, you can test the renovated cleaning mechanism here:

https://cimbali.github.io/CleanLinks/
