### ISSUE TITLE
Firefox mobile google links gives error 404 on all results

### ISSUE THREAD

**Issue by DIGIN4** [Cimbali/CleanLinks#69]

**Comment by Swizzler121** [comment]
I'm getting a similar issue with youtube embeds on desktop firefox. It'll load the player but the video fails to load.

**Comment by Cimbali** [comment]
The rule for youtube embeds has been added a little late as a default Rule on v4. If you don’t have it because you used a v4 beta, you can either:
- click « Reset rules » in the CleanLinks options, or
- Manually add the following rule:
    - domain = `www.youtube.com`
    - path = `^/get_video_info$`
    - remove query parameters `eurl`

**Comment by Cimbali** [comment]
This works for me on the v4 versions. Please reopen with more details if you still run into this issue.
