### ISSUE TITLE
Limitation of all link cleaners when used with Facebook?

### ISSUE THREAD

**Issue by toughdiamond** [Cimbali/CleanLinks#71]
This isn't really an issue with CleanLinks as such, but now I'm more familiar with how Facebook tracking works, I think I've realised a depressing fact - although a good link cleaning utility will remove tracking from any outgoing URL that a user clicks, it's powerless to protect the user from the tracking that gets added to their own URLs when they post them on Facebook, unless of course all the user's Facebook friends are smart enough to use CleanLinks.  So if I understand this right, all that CleanLinks is achieving on Facebook is to protect other people from being tracked, but not the user who actually has the add-on.   Is that correct?

Not that I'm criticizing CleanLinks, I still think it's the best there is.  Just that users might not be aware that they might not be immune from being tracked simply because they're cleaning Facebook's outgoing URLs.

Incidentally, I did find a workaround of sorts to the problem of those shortened URLs that can't be directly cleaned, but it involves copying the text from the Facebook post - the text that shows the true name of the website and the title of the article - and pasting it into a search engine such as DuckDuckGo that doesn't track the user.  Nearly every time, the first hit is the clean, direct link to the page of interest.  I've managed to automate it myself by the use of Mouse Recorder and a few lines of code, which makes the task pretty straightforward, though I don't see how that strategy could be implemented in a link-cleaning add-on, as the process works so differently.  So near and yet so far :-(

**Comment by Cimbali** [comment]
>  So if I understand this right, all that CleanLinks is achieving on Facebook is to protect other people from being tracked, but not the user who actually has the add-on. Is that correct?

It sort of depends what you mean by protecting. Facebook will know how many non-cleanlinks users have opened the link in one of your posts. for example. However CleanLinks is blocking Facebook from knowing on which links you click, and blocking the target sites (to some degree) from knowing e.g. which post you came from. The site is probably still available through the HTTP referer if you did not disable that.

The duckduckgo lookup of shortened URLs is interesting. I’m not sure the add-on can do anything with that, and we certainly don’t want to start maintaining a parallel database of the shortened URLs.

**Comment by toughdiamond** [comment]
I take it a HTTP referer is the same as what I call "tracking parameters" that Facebook (and others) add to the basic URL, normally preceded by a question mark or an ampersand?  My usual way of visiting an outgoing URL from Facebook is to rightclick it and choose "Copy Clean Link,"  then I paste it into a new browser tab which allows me to check it for tracking before hitting return.  Usually it's clean, so I figure I'm entirely protected.  I've always assumed I could also simply click the link to get the same result, but I like to make sure it's not one of those pesky shortened links or any other source of dirt.

When I say that CleanLinks users might not be "protected" when they post URLs on Facebook, what I mean is that when I post my URL, Facebook adds tracking data to it, so when non-CleanLinks users click on the link, the external website picks up that tracking data and knows where those users came from (i.e. my post), and I don't know what else that data tells the website about me. It all hinges on what's in that ?fbclid data. Of course Facebook already knows what I've posted there, so it wasn't really all that private in the first place.

I agree maintaining a database of shortened URLs would be way too hard.  The only thing I can imagine an add-on being able to do easily would be to detect a shortened URL and warn the user before navigating to the page.  But my guess is that a shortened URL at worst can only end up providing data about the user who posted it, and the power to avoid that is presumably in the hands of that user.  My own solution is simply that I never post a shortened URL.

**Comment by Cimbali** [comment]
The referrer is a field in an http request to tell the website you're visiting which page you're coming from, so it's not in the URL. See here to deactivate it:
https://www.technipages.com/firefox-enable-disable-referrer

**Comment by toughdiamond** [comment]
Thanks, I had no idea that was there.  Disabled now :-)  It does raise the question, if I pasted a URL into a new browser tab, where would Firefox say I'd come from, if the referrer was enabled?

**Comment by Cimbali** [comment]
There’s no referrer when you put a link directly in the address bar, as far as I know.

**Comment by toughdiamond** [comment]
That makes sense.  It would have to be very clever to correctly work out where the link had come from every time.
