### ISSUE TITLE
target="_blank" is not honored

### ISSUE THREAD

**Issue by BreadYogurt** [Cimbali/CleanLinks#72]
Cleaned links with the `target="_blank"` tag are not opened in a new tab like they are supposed to. This happens regardless of whether the "Follow Target Attribute" setting is enabled or not.

**Comment by Cimbali** [comment]
Yes this has always been a tricky thing to recreate. Can you please specify browser and its version, the add-on version of CleanLinks and your configuration (basically which of the Features are selected).

**Comment by BreadYogurt** [comment]
My browser is Firefox v68.0.1, CleanLinks is v3.2.7, and here is my configuration:
![Screenshot from 2019-08-02 22-21-54](https://user-images.githubusercontent.com/14959006/62406592-0074d000-b574-11e9-9112-654c2ce52f23.png)
