### ISSUE TITLE
Disable add-on on per-tab basis

### ISSUE THREAD

**Issue by Cimbali** [Cimbali/CleanLinks#76]

**Comment by Cimbali** [comment]
Currently the add-on can only be disabled globally.

**Comment by birdie-github** [comment]
An even better idea: temporary disable for the current tab and its children.

**Comment by Cimbali** [comment]
I’m not sure I get all the subtleties here. 
- What do you call children of a tab?
- When you say temporary, do you mean that it would automatically toggle back on? As opposed to manually toggling the add-on on/off? Or is it something else?
