### ISSUE TITLE
version 4 bug

### ISSUE THREAD

**Issue by Mike-Reddick** [Cimbali/CleanLinks#78]
the new v4, isn't work in FF 67 with e10s disabled, extension toggle and settings buttons etc.

**Comment by Cimbali** [comment]
I’ve just run into the same issue but it works fine on a fresh install… don’t quite know what’s going on, for some reason loading the old preferences is broken. And not being able to load preferences, in turn, breaks everything.

You can temporarily revert to an old version through <https://addons.mozilla.org/en-GB/firefox/addon/clean-links-webext/versions/>

**Comment by Mike-Reddick** [comment]
thanks so much for the new fixed version

**Comment by Mike-Reddick** [comment]
@Cimbali, have a little bug, if I turn off addon in the panel, switching tabs, addon re-enable, or is a new behavior?

**Comment by Cimbali** [comment]
The new feature is that the disable button now works per tab. It you switch it off, then change tabs, and come back to the tab where it's off, it should still be off there.

**Comment by Mike-Reddick** [comment]
ok, then the behavior are right! thanks

**Comment by Mike-Reddick** [comment]
@Cimbali , I'm want suggest add a context menu entry to toggle CL on/off, maybe optional, because some sites open popups without toolbar, so, the user can't access the CL icon to toggle.

**Comment by Cimbali** [comment]
Hi @Mike-Reddick, I’ll look at it. In the mean time, if you want to access add-ons from the toolbar on popups, there is a setting you can toggle, [dom.disable_window_open_feature.toolbar][1].

[1]: https://www.reddit.com/r/firefox/comments/7o5vck/how_to_make_noscript_icon_appear_on_popout_window/

**Comment by Mike-Reddick** [comment]
@Cimbali , to me this solution is perfect, better than a context menu entry, thanks so much for information.
