### ISSUE TITLE
Download files and read and modify the browser’s download history

### ISSUE THREAD

**Issue by Swizzler121** [Cimbali/CleanLinks#79]
Explanation needed as to why you need permission to view and modify download history? seems suspect.

**Comment by Cimbali** [comment]
Hi @Swizzler121, this is explained in the readme. The downloads permission is needed to export the rules file. In the code it is used here:

https://github.com/Cimbali/CleanLinks/blob/301123cf765f233c5d339f101107c7b1b821e8b4/addon/pages/options.js#L435-L442

I’m afraid I can’t ask for the permission to create a download only (without viewing / modifying rights), as it doesn’t exist.

**Comment by Cimbali** [comment]
The v4 non-beta release will not include the downloads permission, as I’ve managed to find a way to work around it.
