### ISSUE TITLE
when putting cleanlinks in firefoxs overflow menu it isnt displayed completely

### ISSUE THREAD

**Issue by elypter** [Cimbali/CleanLinks#8]
i have a 1280x800 screen and it isnt enough to display the whole addon because the overflow menu reduces the addons width and has no overflow scroll bars. it might be more of a problem on mozillas side but maybe some of the text could be put in a collapsible container or a tooltip to accommodate those shortcomings.

**Comment by Cimbali** [comment]
I'm sorry I didn't quite get what's happening. The popup window is too wide for your screen? It'as about 1/4th of mine and I have 1920px. Can you maybe take a screenshot to see where I can add scroll bars?

**Comment by elypter** [comment]
the height is the problem. the width is determined by the overflow menu. i couldnt make a screenshot because the hotkey closes the menu. just put it there and try it out. it is a feature for firefox introduced not too long ago to save space in the adress bar if you have a lot of addons installed.

**Comment by Cimbali** [comment]
OK so if the plugin is (low enough) in the overflow menu, the plugin's bottom might get clipped/rendered off-screen.

I'll give it a try and see what I can come up with.

**Comment by Cimbali** [comment]
@elypter Should be fixed in 3.0b4, feel free to reopen if it doesn't work for you.
