### ISSUE TITLE
Infinite redirects when logging in on various websites

### ISSUE THREAD

**Issue by rsnyman** [Cimbali/CleanLinks#80]
CleanLinks v4.0.0b2

When I try logging into various sites, I end up with an infinite redirect.

Sites affected:
- mail.google.com
- linode.com
- gandi.net

I'm using the default settings and rules, no custom or extra ones. I have to disable CleanLinks on those sites in order to be able to use them.

Unfortunately I don't see a way to capture any logs CleanLinks might have in order for you to see what is going on.

**Comment by Cimbali** [comment]
Clicking on the CleanLinks icon you can see the list of cleaned links and whitelist those sites. I'll add gmail and gandi to the default rules but I don't know the other website.

**Comment by Cimbali** [comment]
Closing as the gandi and google rules are added. Feel free to reopen with the necessary linode.com URL pattern if you think it should be in the default rules. Otherwise it can just be in you own set of rules.

**Comment by rsnyman** [comment]
Thanks @Cimbali 

FYI Linode is a popular VPS service, like Digital Ocean.

**Comment by Cimbali** [comment]
There’s a lot of very popular websites on which I don’t have accounts, so I can’t find out what the correct rules are for whitelisting.
