### ISSUE TITLE
Why CleanLinks requests additional rights (like "Download") which are not mentioned anywhere.

### ISSUE THREAD

**Issue by OderDochNicht** [Cimbali/CleanLinks#81]
Today FireFox told me that to update CleanLinks new access rights were necessary. One was "Download" the other one I don't remember exactly (and I cannot retrieve it any more).
For what part of it's function, "Download" is needed?
The second one was also seem hardly necessary for the function of CleanLinks.

Bug or was CleanLinks sold to some wierd russian software developers which too much money?

**Comment by Cimbali** [comment]
Neither ! This was explained in #79 and in the README while still applicable. I used the downloads permission to export the rules files, but I’ve now found a way to achieve this without the permission. Non-beta releases of version 4 will not require this additional permission (actually v4.0.0b4 already does not require it).
