### ISSUE TITLE
Since the update to 4.0.0b2 this causes my Gmail to constantly reload

### ISSUE THREAD

**Issue by JobLeonard** [Cimbali/CleanLinks#82]
So since a day or two Gmail refused to open in its default form, and after systematically enabling/disabling add-ons I isolated it to the latest update to CleanLinks. I'm not sure what could be triggering it, really, because I don't see it actually *do* anything when I open the devtools.

**Comment by Cimbali** [comment]
Thanks for reporting ! Will fix the default rules in the next release (as gmail is quite common I’ll make one just for this, should be on AMO soon).
