### ISSUE TITLE
Sort by addition order

### ISSUE THREAD

**Issue by Mike-Reddick** [Cimbali/CleanLinks#84]
Please if possible add a option to sort rules by addition date.

**Comment by Cimbali** [comment]
I’m afraid that information is not available in the rules currently.

**Comment by Mike-Reddick** [comment]
thanks the attention

**Comment by Mike-Reddick** [comment]
I just suggested it, because sorting by date you can know easily what rules is default rules, and what is added after by the user.

**Comment by Cimbali** [comment]
I think we’ll have to settle for a user rules / default rules filter, not a full sorting, at least for now. That will also help solve #86

**Comment by Mike-Reddick** [comment]
Yes no need be exactly a sort feature, a user rules / default rules filter can give the same effect, even better effect, I think the important is something to separate user rules of default rules, maybe even a different color etc. Sorry I needed be more specific in the first post.

**Comment by khabib227** [comment]
thanks for the "rule origin" feature
