### ISSUE TITLE
Incorrect Amazon Filter

### ISSUE THREAD

**Issue by OdinVex** [Cimbali/CleanLinks#88]
Trying to login to Amazon,  CleanLinks ends up returning a clean link of "https://specs.openid.net/auth/2.0/identifier_select" instead. Original url: "https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&openid.return_to=STRIPPED_B64&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=usflex&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0"

**Comment by Cimbali** [comment]
There is already a rule with

- domain = `amazon.*`
- path = `/ap/signin`
- whitelist = `openid.returned_to`

The easiest would be to remove this whitelist item and replace it with `openid\..+`

**Comment by OdinVex** [comment]
Unfortunately, that doesn't help mine. I don't mind those vars being removed anyway, they aren't necessary on my end. (Manually logged in with openid vars removed works for me but CleanLinks won't filter it correctly on its own.)

https://www.amazon.com/ap/signin?openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.amazon.com%2F%3Fref_%3Dnav_ya_signin&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=usflex&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0http://specs.openid.net/auth/2.0/identifier_select

Ends up being http://specs.openid.net/auth/2.0/identifier_select.

**Comment by Cimbali** [comment]
That rule I suggested seems not to be applied if the bug you’re saying is still happening. Note that it is not released (yet), as CleanLinks does not get its rules online, so you have to make this modification in the rules yourself.

If you have, that might be a whole different problem. Can you export your rules file and upload it so I can compare it with the defaults one? Also, what’s the version you’re running?

**Comment by OdinVex** [comment]
Stock rules (reset), then modified openid as you mentioned (saved), reloaded browser, still problematic. v4.0.4.

[clean_links_rules.txt](https://github.com/Cimbali/CleanLinks/files/4357440/clean_links_rules.txt)

**Comment by Cimbali** [comment]
@OdinVex Was this fixed by v4.0.5 ?

**Comment by OdinVex** [comment]
> @OdinVex Was this fixed by v4.0.5 ?

I just checked, yes. Not sure why it wasn't working, my rules JSON hasn't changed except for shields.io.

**Comment by Cimbali** [comment]
Only the rules changed, so the good news is that applying these rules is not problematic.

The bug is most likely that the background CleanLinks process did not properly reload the rules after you edited them. I’ll keep an eye out for this bug if it pops back up.

In the mean time, at least the amazon login works fine.

**Comment by OdinVex** [comment]
Yet reloading the browser didn't reload the rules...hm.
