### ISSUE TITLE
YouTube embeds do not work

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#91]
Sample URL: https://wccftech.com/crytek-invites-developers-to-try-out-cryengine-on-android/

Log:
```
https://www.youtube.com/embed/tyTTVuG6vcw?feature=oembed
-> https://www.youtube.com/embed/tyTTVuG6vcw
```

Firefox 74/Clean Links v4.0.6, with all options reset to defaults.

**Comment by birdie-github** [comment]
After removing "feature" they still don't work:

https://www.youtube.com/get_video_info?html5=1&video_id=tyTTVuG6vcw&cpn=j7jE7WL0C-mR8c7C&eurl=https%3A%2F%2Fwww.youtube.com%2Fembed%2FtyTTVuG6vcw%3Ffeature%3Doembed&el=embedded&hl=en_US&sts=18338&lact=6&c=WEB_EMBEDDED_PLAYER&cver=20200319&cplayer=UNIPLAYER&cbr=Firefox&cbrver=74.0&cos=Windows&cosver=10.0&width=740&height=342&ei=GxN5XufWMf-SxN8PhPqkgAI&iframe=1&embed_config=%7B%7D

-> https://www.youtube.com/get_video_info?html5=1&video_id=tyTTVuG6vcw&cpn=j7jE7WL0C-mR8c7C&el=embedded&hl=en_US&sts=18338&lact=6&c=WEB_EMBEDDED_PLAYER&cver=20200319&cplayer=UNIPLAYER&cbr=Firefox&cbrver=74.0&cos=Windows&cosver=10.0&width=740&height=342&ei=GxN5XufWMf-SxN8PhPqkgAI&iframe=1&embed_config=%7B%7D

**Comment by Cimbali** [comment]
This embed works fine for me  with a fresh CleanLinks 4.0.6 and FF 73. Do you have other add-ons that might interfere?

**Comment by birdie-github** [comment]
Yes, it looks like a combination of uBlock Origin (with default rules) and Clean Links breaks things. Only it all becomes so complicated I don't know where to look how to debug all of this.

**Comment by birdie-github** [comment]
After force-refreshing uBlock Origin filter lists everything is now working. Let's close this issue until I find a way to reproduce it.
