### ISSUE TITLE
Query parameters sorting

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#92]
Currently not implemented which makes it extremely hard to find the match.

**Comment by Cimbali** [comment]
I’m not sure where you mean this. In the parameter section when editing rules?

**Comment by birdie-github** [comment]
This list:

![actions](https://user-images.githubusercontent.com/4958603/77362419-c9dd0700-6d48-11ea-99e3-a1a22c47ce90.png)

is not sorted in any shape or form.
