### ISSUE TITLE
Disqus comments completely don't work

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#95]
Example URL: https://wccftech.com/crytek-invites-developers-to-try-out-cryengine-on-android/

**Comment by Cimbali** [comment]
Editing the current disqus rule `disqus.com/^/embed/comments` to also either whitelist or delete (both work) the parameter `t_i` fixes this for me. Will update the rules.

**Comment by birdie-github** [comment]
Disqus is quite important and used on literally millions of domains.

It would be great if you kept an eye on it because otherwise lots of users will be upset and reviews will be harsh.

**Comment by Cimbali** [comment]
Thanks for your feedback. I’m fully committed to making the best add-on possible with the limited time I have on my hands. Nonetheless, a couple of things need to be taken into account:

- Even if I wanted, I couldn’t possibly keep up with all the websites. Making good default rules has to be a community effort.
- CleanLinks always has been (and will remain for the foreseeable future) for advanced users − that can tolerate sites breaking occasionally, and fixing them. Think uMatrix more than uBlock Origin.
- Following these 2 points, CleanLinks allows rules to be edited directly, without needing to wait for a rules or add-on update.
