### ISSUE TITLE
Query parameters list is hard to read/understand

### ISSUE THREAD

**Issue by birdie-github** [Cimbali/CleanLinks#96]
As far as I understand it shows per domain query parameters (with a red X next to them) and global/higher domain query parameters (as grey) all in the same list.

It's all kinda cryptic because you cannot remove grey parameters.

It would be great to have hints or when grey parameters are clicked you're redirected to a proper rule.

**Comment by Cimbali** [comment]
This is (partially) planned in #87 as you can see on the screenshots: we’ll get a clickable display of all the rules the current rule is editing from.

On hints, the “help” tooltip on editing cleaning actions explains that grey means inherited rules. 
If you have any further suggestions on this I’m listening.

**Comment by Cimbali** [comment]
Tracked in #92 + #87
